// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceUIClient is the client API for ServiceUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceUIClient interface {
	// ListInstanceSpecs returns a list of Service Instance(s) that can be started through the UI.
	ListInstanceSpecs(ctx context.Context, in *ListInstanceSpecsRequest, opts ...grpc.CallOption) (ServiceUI_ListInstanceSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type serviceUIClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceUIClient(cc grpc.ClientConnInterface) ServiceUIClient {
	return &serviceUIClient{cc}
}

func (c *serviceUIClient) ListInstanceSpecs(ctx context.Context, in *ListInstanceSpecsRequest, opts ...grpc.CallOption) (ServiceUI_ListInstanceSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServiceUI_ServiceDesc.Streams[0], "/v1.ServiceUI/ListInstanceSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceUIListInstanceSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceUI_ListInstanceSpecsClient interface {
	Recv() (*ListInstanceSpecsResponse, error)
	grpc.ClientStream
}

type serviceUIListInstanceSpecsClient struct {
	grpc.ClientStream
}

func (x *serviceUIListInstanceSpecsClient) Recv() (*ListInstanceSpecsResponse, error) {
	m := new(ListInstanceSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ServiceUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceUIServer is the server API for ServiceUI service.
// All implementations must embed UnimplementedServiceUIServer
// for forward compatibility
type ServiceUIServer interface {
	// ListInstanceSpecs returns a list of Service Instance(s) that can be started through the UI.
	ListInstanceSpecs(*ListInstanceSpecsRequest, ServiceUI_ListInstanceSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedServiceUIServer()
}

// UnimplementedServiceUIServer must be embedded to have forward compatible implementations.
type UnimplementedServiceUIServer struct {
}

func (UnimplementedServiceUIServer) ListInstanceSpecs(*ListInstanceSpecsRequest, ServiceUI_ListInstanceSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListInstanceSpecs not implemented")
}
func (UnimplementedServiceUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedServiceUIServer) mustEmbedUnimplementedServiceUIServer() {}

// UnsafeServiceUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceUIServer will
// result in compilation errors.
type UnsafeServiceUIServer interface {
	mustEmbedUnimplementedServiceUIServer()
}

func RegisterServiceUIServer(s grpc.ServiceRegistrar, srv ServiceUIServer) {
	s.RegisterService(&ServiceUI_ServiceDesc, srv)
}

func _ServiceUI_ListInstanceSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInstanceSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceUIServer).ListInstanceSpecs(m, &serviceUIListInstanceSpecsServer{stream})
}

type ServiceUI_ListInstanceSpecsServer interface {
	Send(*ListInstanceSpecsResponse) error
	grpc.ServerStream
}

type serviceUIListInstanceSpecsServer struct {
	grpc.ServerStream
}

func (x *serviceUIListInstanceSpecsServer) Send(m *ListInstanceSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ServiceUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceUI_ServiceDesc is the grpc.ServiceDesc for ServiceUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ServiceUI",
	HandlerType: (*ServiceUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ServiceUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInstanceSpecs",
			Handler:       _ServiceUI_ListInstanceSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service-ui.proto",
}
